TAREGET = main
INCL = -I ./
cxx = g++
OPT = -g
CXXFLAGS = -g -std = c++11# -Wall

OBJ = $(Target).o integer_action.o

integer_action.o: action_base.hpp integer_action.hpp

$(TARGET): $(OBJ)
	g++ -o $(TARGET) $(CFLAGS) $(INCL)


